report: "report/workflow.rst"
#configfile: "config/config.yaml"

with open('SraAccList.txt', 'r') as file:
    samples = file.read().splitlines()

shell.executable("/bin/sh") # sra-tools container doesn't have bash

rule all:
    input:
        expand('fastq/{sample}_1.fastq', sample=samples),
        expand('fastq/{sample}_2.fastq', sample=samples),
        'ASVs_taxonomy.tsv'

rule sra_prefetch:
    retries: 3
    output:
        temp('{sample}/{sample}.sra')
    container:
        'docker://ncbi/sra-tools:3.0.1'
    threads: 1
    resources:
        mem_mb=1000,
        runtime=480
    shell:
        'prefetch {wildcards.sample}'

rule sra_to_fastq:
    input:
        '{sample}/{sample}.sra'
    output:
        'fastq/{sample}_1.fastq',
        'fastq/{sample}_2.fastq'
    container:
        'docker://ncbi/sra-tools:3.0.1'
    threads: 4
    resources:
        mem_mb=2000,
        runtime=480
    shell:
        'fasterq-dump --skip-technical --mem 1GB --threads 4 --split-files -O fastq/ {wildcards.sample}'

rule dada2_paired:
    input:
        expand('fastq/{sample}_1.fastq', sample=samples),
        expand('fastq/{sample}_2.fastq', sample=samples)
    output:
        'summary.tsv',
        'ASV.tsv',
        'asv.rds',
        'ASVs.fa',
        'ASVs_taxonomy.tsv'
    threads: 4
    resources:
        mem_mb=32000,
        runtime=1440
    shell:
        'singularity exec dada2_1.14.0a.sif Rscript scripts/process_paired_end.R'
    #container:
    #    'docker://blekhmanlab/dada2:1.18.0'
    #shell:
    #    'Rscript scripts/process_paired_end.R'
