report: "report/workflow.rst"
#configfile: "config/config.yaml"

with open('SraAccList.txt', 'r') as file:
    samples = file.read().splitlines()

rule all:
    input:
        expand('fastq/{sample}_1.fastq', sample=samples),
        expand('fastq/{sample}_2.fastq', sample=samples),

rule sra_prefetch:
    retries: 3
    output:
        temp('{sample}/{sample}.sra')
    container:
        'docker://ncbi/sra-tools:3.0.1'
    shell:
        'prefetch {wildcards.sample} -O results/data/sra/'

rule sra_to_fastq:
    input:
        '{sample}/{sample}.sra'
    output:
        'fastq/{sample}_1.fastq',
        'fastq/{sample}_2.fastq'
    container:
        'docker://ncbi/sra-tools:3.0.1'
    shell:
        'fasterq-dump --skip-technical --mem 1GB --threads 4 --split-files -O {output} {wildcards.sample}'
