# Where are shared resources stored? (e.g. container images, silva db)
# NOTE: This currently needs to be pull into the R scripts manually
resources_path: '/panfs/roc/groups/7/blekhman/shared/cmanager/resources/'
